/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("com.github.johnrengelman.shadow") version "8.1.1"
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    mavenCentral()

    maven {
        url = uri("https://jitpack.io/")
    }

    maven {
        name = "papermc"
        url = uri("https://repo.papermc.io/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.mikeprimm.com/")
    }

    maven {
        url = uri("https://repo.onarandombox.com/content/groups/public/")
    }

    maven {
        url = uri("https://repo.codemc.org/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.wea-ondara.net/repository/public/")
    }

    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    maven {
        url = uri("https://repo.wea-ondara.net/repository/maven-releases/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }

    maven {
        url = uri("https://github.com/Multiverse/Multiverse-Core/")
    }
}

dependencies {
    // paper mc
    compileOnly("io.papermc.paper:paper-api:1.18.2-R0.1-SNAPSHOT")

    api(libs.org.bstats.bstats.bukkit)
    api(libs.org.bstats.bstats.bungeecord)
    api("com.google.code.gson:gson:2.13.1")
    api("org.apache.commons:commons-lang3:3.18.0")
    api("org.jetbrains:annotations:26.0.2")
    api("org.yaml:snakeyaml:2.0")
    testImplementation(libs.junit.junit)
    compileOnly("net.md-5:bungeecord-api:1.21-R0.3")
    implementation("net.md-5:bungeecord-chat:1.21-R0.3")
    compileOnly("com.github.milkbowl:VaultAPI:1.7")
    compileOnly("org.dynmap:dynmap-api:2.0")
    compileOnly("org.mvplugins.multiverse.core:multiverse-core:5.1.2")
    compileOnly(libs.com.gmail.nossr50.mcmmo.mcmmo)
    compileOnly(libs.net.alpenblock.bungeeperms)
    compileOnly(libs.net.luckperms.api)
}

group = "com.github.ucchyocean"
version = "3.1.0"
description = "LunaChat"

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(17))
    withSourcesJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}

tasks.shadowJar {
    archiveClassifier.set("")

    relocate("org.bstats", "com.github.ucchyocean.shadow.bstats")

    minimize()
}

tasks.build {
    dependsOn(tasks.shadowJar)
}